name: brew check

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  check:
    strategy:
      matrix:
        os: [ macos-15-intel, macos-26 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Tap local repo
        run: brew tap vacs-project/tap .

      - name: brew style
        run: brew style --cask vacs-project/tap/vacs
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}

      - name: brew audit
        run: brew audit --cask --online vacs-project/tap/vacs
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
